name: Hourly Website Check
on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-website:
    runs-on: ubuntu-22.04  # Specify an older Ubuntu version for better package compatibility
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2 \
          libicu-dev \
          libffi-dev \
          x264 \
          --fix-missing
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright
      run: |
        playwright install
        playwright install-deps
        
    - name: Run Playwright script
      run: python runner.py
