name: Daily Price Data Collection

on:
  schedule:
    # Runs at 8:00 AM IST (2:30 AM UTC) every day
    - cron: '30 2 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-price-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
        playwright install-deps

    - name: Run price collection script
      run: python script_name.py  # Replace with your script's filename

    - name: Upload CSV file
      uses: actions/upload-artifact@v4
      with:
        name: price-data-${{ github.run_number }}
        path: data/*.csv
        retention-days: 90

    - name: Commit files
      run: |
        git config --local user.name "GitHub Action"
        git add data/*.csv
        git commit -m "Add price data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
